const data={
6:{name:"AI Foundations",vn:"AI quanh em và sử dụng AI an toàn",role:"AI Explorer",product:"AI Learning Portfolio",prompt:"Task + Context + Output",message:"AI hỗ trợ em, nhưng em vẫn chịu trách nhiệm.",lessons:["AI là gì?","AI quanh em","AI hoạt động như thế nào?","Con người và AI","AI có thể sai","Fact-checking với AI","Dữ liệu cá nhân là gì?","An toàn và quyền riêng tư","Cách đặt câu hỏi hiệu quả","AI hỗ trợ học tập","Human + AI Challenge","Portfolio & Reflection"]},
7:{name:"How Machines Learn",vn:"Máy học từ dữ liệu",role:"AI Learner",product:"Mini Machine Learning Project",prompt:"Task + Context + Input + Output",message:"AI học từ dữ liệu; dữ liệu tốt hơn tạo ra AI tốt hơn.",lessons:["AI học khác con người?","Data – nhiên liệu của AI","Thu thập và gán nhãn dữ liệu","Training Data vs Testing Data","Supervised Learning","Unsupervised Learning","Reinforcement Learning","Thực hành Teachable Machine","Bad Data → Bad AI","Bias & Fairness","Mini AI Project","Test – Improve – Present"]},
8:{name:"Generative AI & Digital Responsibility",vn:"AI tạo sinh và trách nhiệm số",role:"Responsible AI User",product:"Responsible AI Creation",prompt:"Format + Constraint + Disclosure",message:"Sáng tạo cùng AI, không sao chép từ AI.",lessons:["Từ Machine Learning đến GenAI","AI tạo nội dung thế nào?","AI Hallucination","Deepfake & Synthetic Media","Recommendation & Manipulation","Privacy & Digital Footprint","Copyright thời GenAI","Academic Integrity","AI Disclosure","Human Creativity vs AI","Responsible AI Creation","Peer Review & Reflection"]},
9:{name:"AI Problem Solving & Future Skills",vn:"Giải quyết vấn đề và kỹ năng tương lai",role:"AI Problem Solver",product:"AI Solution Prototype",prompt:"Prompt → Evaluate → Revise",message:"Đừng bắt đầu bằng AI. Hãy bắt đầu bằng một vấn đề.",lessons:["AI đang thay đổi xã hội","Jobs & Skills in the AI Era","Human Skills","AI Bias & Social Impact","Misinformation & Deepfake","Fact-checking Workflow","Problem Finding","Solution Ideation","Data Requirements","Build Prototype","Test – Evaluate – Improve","AI Solution Pitch"]},
10:{name:"AI Literacy & Prompt Engineering",vn:"Hiểu biết AI và kỹ thuật viết prompt",role:"AI Collaborator",product:"AI Learning Assistant",prompt:"Role + Task + Context + Input + Format + Constraint",message:"Tư duy tốt hơn tạo ra prompt tốt hơn.",lessons:["Generative AI & LLM","Prediction vs Generation","LLM tạo câu trả lời","Hallucination & Limitations","Prompt Engineering","6 thành phần của Prompt","Prompt Iteration","AI for Research","AI for Learning","AI for Creativity","Design an AI Learning Assistant","Test – Evaluate – Reflection"]},
11:{name:"AI Systems & Intelligent Applications",vn:"Hệ thống AI và ứng dụng thông minh",role:"AI System Designer",product:"AI System Prototype",prompt:"Examples + System Instructions + Knowledge Context",message:"Một sản phẩm AI là một hệ thống, không chỉ là chatbot.",lessons:["From AI Tool to AI System","Anatomy of an AI System","Natural Language Processing","Computer Vision","Neural Networks","Classification & Clustering","Advanced Prompting","System Instructions","RAG & Grounded Prompting","AI System Design","Prototype Development","Demonstration & Evaluation"]},
12:{name:"Responsible AI Innovation",vn:"Đổi mới AI có trách nhiệm",role:"Responsible AI Innovator",product:"AI Capstone Proposal",prompt:"Workflow + Guardrails + Human Oversight",message:"AI làm được không có nghĩa là AI nên làm.",lessons:["AI System Lifecycle","Human Oversight","Responsible AI Principles","AI Risk Classification","Privacy & Data Governance","Fairness & Bias","Transparency & Guardrails","Accountability","AI Impact Assessment","AI Capstone Design","Risk Review & Improvement","AI Innovation Pitch"]}}
const outcomes={"Thực hành Teachable Machine":"Huấn luyện mô hình phân loại ảnh, kiểm thử bằng dữ liệu mới và giải thích ảnh hưởng của chất lượng dữ liệu.","Bias & Fairness":"Kiểm thử với nhiều người hoặc điều kiện khác nhau và nhận biết thiên lệch.","Fact-checking với AI":"Kiểm chứng thông tin bằng nguồn đáng tin cậy.","Portfolio & Reflection":"Tổng hợp minh chứng, tự đánh giá và phản tư."};
const modules=["UNDERSTAND","USE & EVALUATE","ETHICS & RESPONSIBILITY","CREATE"];
let grade=7,active=7,query="";let done=JSON.parse(localStorage.getItem("ai-progress")||"[]");
const $=id=>document.getElementById(id);const outcome=t=>outcomes[t]||`Hoàn thành hoạt động học tập về “${t}”, trình bày bằng chứng và phản tư về trách nhiệm của người học.`;
function setGrade(g){grade=+g;active=0;render()};function setLesson(i){active=i;renderPlan();document.querySelector("#ke-hoach").scrollIntoView({behavior:"smooth"})}
function toggle(i){const k=`${grade}-${i}`;done=done.includes(k)?done.filter(x=>x!==k):[...done,k];localStorage.setItem("ai-progress",JSON.stringify(done));renderLessons()}
function render(){const g=data[grade];$("grades").innerHTML=Object.keys(data).map(x=>`<button class="${+x===grade?'active':''}" onclick="setGrade(${x})">${x}</button>`).join("");$("path").innerHTML='<p>LỘ TRÌNH 6–12</p>'+Object.keys(data).map((x,i)=>`<button class="${+x===grade?'active':''}" onclick="setGrade(${x})"><span>0${i+1}</span><b>${data[x].role}</b><small>Khối ${x}</small></button>`).join("");$("summary").innerHTML=`<div><span class="number">${grade}</span><p>KHỐI</p></div><div><p class="eyebrow">${g.name}</p><h3>${g.vn}</h3><blockquote>“${g.message}”</blockquote></div><dl><div><dt>Vai trò</dt><dd>${g.role}</dd></div><div><dt>Sản phẩm cuối</dt><dd>${g.product}</dd></div><div><dt>Prompting</dt><dd>${g.prompt}</dd></div></dl>`;renderLessons();renderPlan()}
function renderLessons(){const g=data[grade];$("lessons").innerHTML=g.lessons.map((t,i)=>({t,i})).filter(x=>(x.t+outcome(x.t)).toLowerCase().includes(query)).map(({t,i})=>{const k=`${grade}-${i}`;return `<article class="${active===i?'selected':''}" onclick="setLesson(${i})"><div class="lesson-top"><span>TIẾT ${String(i+1).padStart(2,'0')}</span><button aria-label="Đánh dấu hoàn thành" onclick="event.stopPropagation();toggle(${i})">${done.includes(k)?'✓':'○'}</button></div><h4>${t}</h4><p>${outcome(t)}</p><footer><span>${modules[Math.floor(i/3)]}</span><b>Xem kế hoạch →</b></footer></article>`}).join("");const p=Math.round(g.lessons.filter((_,i)=>done.includes(`${grade}-${i}`)).length/12*100);$("bar").style.width=p+"%";$("progressText").textContent=p+"% hoàn thành"}
function renderPlan(){const g=data[grade],t=g.lessons[active];$("lessonNo").textContent=`Tiết ${active+1}`;$("asideTitle").textContent=t;$("module").textContent=`KHỐI ${grade} • ${modules[Math.floor(active/3)]}`;$("planTitle").textContent=t;$("objective").innerHTML=`<b>Học sinh có thể:</b> ${outcome(t)}`;$("lessonNav").innerHTML=g.lessons.map((x,i)=>`<button class="${i===active?'active':''}" onclick="setLesson(${i})"><span>${String(i+1).padStart(2,'0')}</span>${x}</button>`).join("");$("tmLab").innerHTML=grade===7&&active>=7?`<div class="tm-lab"><div><p class="eyebrow">TEACHABLE MACHINE LAB</p><h3>Huấn luyện mô hình, không thu thập dữ liệu cá nhân</h3><p>Tạo 2–3 lớp ảnh đồ vật an toàn, mỗi lớp tối thiểu 30 mẫu; thay đổi góc nhìn và ánh sáng; kiểm thử bằng dữ liệu chưa dùng khi huấn luyện.</p><a href="https://teachablemachine.withgoogle.com/train/image" target="_blank" rel="noreferrer">Mở Teachable Machine ↗</a></div><ol><li><b>Đặt mục tiêu</b><span>Không sử dụng dữ liệu khuôn mặt.</span></li><li><b>Tạo dữ liệu</b><span>Cân bằng số mẫu và đa dạng điều kiện.</span></li><li><b>Train & Test</b><span>Kiểm thử với mẫu hoàn toàn mới.</span></li><li><b>Improve</b><span>Ghi lỗi, bổ sung dữ liệu và huấn luyện lại.</span></li></ol></div>`:""}
$("search").addEventListener("input",e=>{query=e.target.value.toLowerCase();renderLessons()});$("print").onclick=()=>window.print();render();
