const data={
6:{name:"AI Foundations",vn:"AI quanh em và sử dụng AI an toàn",role:"AI Explorer",product:"AI Learning Portfolio",prompt:"Task + Context + Output",message:"AI hỗ trợ em, nhưng em vẫn chịu trách nhiệm.",lessons:["AI là gì?","AI quanh em","AI hoạt động như thế nào?","Con người và AI","AI có thể sai","Fact-checking với AI","Dữ liệu cá nhân là gì?","An toàn và quyền riêng tư","Cách đặt câu hỏi hiệu quả","AI hỗ trợ học tập","Human + AI Challenge","Portfolio & Reflection"]},
7:{name:"How Machines Learn",vn:"Máy học từ dữ liệu",role:"AI Learner",product:"Mini Machine Learning Project",prompt:"Task + Context + Input + Output",message:"AI học từ dữ liệu; dữ liệu tốt hơn tạo ra AI tốt hơn.",lessons:["AI học khác con người?","Data – nhiên liệu của AI","Thu thập và gán nhãn dữ liệu","Training Data vs Testing Data","Supervised Learning","Unsupervised Learning","Reinforcement Learning","Thực hành Teachable Machine","Bad Data → Bad AI","Bias & Fairness","Mini AI Project","Test – Improve – Present"]},
8:{name:"Generative AI & Digital Responsibility",vn:"AI tạo sinh và trách nhiệm số",role:"Responsible AI User",product:"Responsible AI Creation",prompt:"Format + Constraint + Disclosure",message:"Sáng tạo cùng AI, không sao chép từ AI.",lessons:["Từ Machine Learning đến GenAI","AI tạo nội dung thế nào?","AI Hallucination","Deepfake & Synthetic Media","Recommendation & Manipulation","Privacy & Digital Footprint","Copyright thời GenAI","Academic Integrity","AI Disclosure","Human Creativity vs AI","Responsible AI Creation","Peer Review & Reflection"]},
9:{name:"AI Problem Solving & Future Skills",vn:"Giải quyết vấn đề và kỹ năng tương lai",role:"AI Problem Solver",product:"AI Solution Prototype",prompt:"Prompt → Evaluate → Revise",message:"Đừng bắt đầu bằng AI. Hãy bắt đầu bằng một vấn đề.",lessons:["AI đang thay đổi xã hội","Jobs & Skills in the AI Era","Human Skills","AI Bias & Social Impact","Misinformation & Deepfake","Fact-checking Workflow","Problem Finding","Solution Ideation","Data Requirements","Build Prototype","Test – Evaluate – Improve","AI Solution Pitch"]},
10:{name:"AI Literacy & Prompt Engineering",vn:"Hiểu biết AI và kỹ thuật viết prompt",role:"AI Collaborator",product:"AI Learning Assistant",prompt:"Role + Task + Context + Input + Format + Constraint",message:"Tư duy tốt hơn tạo ra prompt tốt hơn.",lessons:["Generative AI & LLM","Prediction vs Generation","LLM tạo câu trả lời","Hallucination & Limitations","Prompt Engineering","6 thành phần của Prompt","Prompt Iteration","AI for Research","AI for Learning","AI for Creativity","Design an AI Learning Assistant","Test – Evaluate – Reflection"]},
11:{name:"AI Systems & Intelligent Applications",vn:"Hệ thống AI và ứng dụng thông minh",role:"AI System Designer",product:"AI System Prototype",prompt:"Examples + System Instructions + Knowledge Context",message:"Một sản phẩm AI là một hệ thống, không chỉ là chatbot.",lessons:["From AI Tool to AI System","Anatomy of an AI System","Natural Language Processing","Computer Vision","Neural Networks","Classification & Clustering","Advanced Prompting","System Instructions","RAG & Grounded Prompting","AI System Design","Prototype Development","Demonstration & Evaluation"]},
12:{name:"Responsible AI Innovation",vn:"Đổi mới AI có trách nhiệm",role:"Responsible AI Innovator",product:"AI Capstone Proposal",prompt:"Workflow + Guardrails + Human Oversight",message:"AI làm được không có nghĩa là AI nên làm.",lessons:["AI System Lifecycle","Human Oversight","Responsible AI Principles","AI Risk Classification","Privacy & Data Governance","Fairness & Bias","Transparency & Guardrails","Accountability","AI Impact Assessment","AI Capstone Design","Risk Review & Improvement","AI Innovation Pitch"]}}
const frameworkLessons={
6:["AI do con người tạo ra","Con người quyết định với AI","Học hỏi và phát triển cùng AI","Mặt tốt và hạn chế của AI","An toàn và minh bạch khi dùng AI","Quyền riêng tư và dữ liệu cá nhân","Dữ liệu – thuật toán – mô hình","AI quanh em và tác động đến gia đình","Các công nghệ AI quen thuộc","Khi nào nên và không nên dùng AI","Giới hạn của AI so với con người","Human + AI Portfolio"],
7:["Con người giữ quyền quyết định","Xác thực kết quả do AI tạo","Quyền tự chủ của con người","Đánh giá một ứng dụng AI an toàn","Trách nhiệm và khai báo sử dụng AI","Đạo đức của dữ liệu huấn luyện","Ba cách học cơ bản của AI","Thực hành Teachable Machine","Dữ liệu sạch và công bằng","Ý tưởng dự án AI từ thực tiễn","Lập kế hoạch dự án AI","Tạo – kiểm thử – trình bày sản phẩm"],
8:["AI không thay thế con người","Rủi ro khi lạm dụng AI tạo sinh","Theo dõi và thao túng bằng AI","Người dùng, người tạo và trách nhiệm pháp lý","Nhận diện và phân loại rủi ro AI","Bảo vệ dữ liệu, bản quyền và trách nhiệm giải trình","AI đọc – nghe – nhìn như thế nào","Nhận diện cảm xúc và giới hạn","Kịch bản hội thoại với AI","Xác định vấn đề cho dự án AI","Thiết kế trải nghiệm người dùng tốt","Dự án chatbot hoặc mô hình nhận dạng"],
9:["Thách thức xã hội trong kỉ nguyên AI","AI tác động đến xã hội","Năng lực và nghề nghiệp tương lai","Trách nhiệm khi sử dụng AI","Phát hiện nội dung giả mạo","Kiến tạo AI công bằng","Vận dụng AI giải quyết vấn đề","Cải thiện dữ liệu và chất lượng sản phẩm","Kiểm chứng và khai báo sản phẩm AI","Con người đồng sáng tạo và dẫn dắt AI","Thiết kế phép thử sản phẩm AI","Phân tích kết quả và cải tiến"],
10:["Con người trong hệ thống AI","Rủi ro của dự án AI","Luật pháp và quyền người dùng","Tuân thủ quy định khi dùng AI","Đạo đức trong vận hành và sáng tạo AI","Minh bạch nội dung do AI tạo","Ứng dụng AI cho vấn đề thực tế Việt Nam","Prompt phù hợp mục tiêu","AI tạo sinh – phân loại – dự đoán","Ý tưởng và thành phần hệ thống AI","Vận hành, phản hồi và tối ưu","Thiết kế AI Learning Assistant"],
11:["Quy trình sử dụng AI an toàn","AI nâng cao năng lực con người","Bền vững, công bằng và quyền dữ liệu","Phân loại rủi ro và sự cố AI","Sơ đồ đạo đức trong thiết kế AI","Quyền được biết, đồng ý và yêu cầu xoá dữ liệu","AI hỗ trợ học tập và thiết kế công cụ","Prompt nâng cao và chia nhỏ nhiệm vụ","NLP – thị giác máy tính – RAG","Thiết kế tổng thể hệ thống AI","Vận hành và tối ưu hệ thống","AI System Prototype"],
12:["Quyền kiểm soát trong vòng đời AI","Vai trò con người trong quyết định","Trách nhiệm công dân trong xã hội AI","Nguyên tắc đạo đức khi thiết kế AI","Phân loại mức độ rủi ro","Trách nhiệm trong hệ sinh thái AI","Công cụ mở để phát triển hệ thống AI","Overfitting, hàm mục tiêu và tối ưu","Thu thập và cải thiện dữ liệu","Phân tích phương án thiết kế hệ thống","Vai trò nhóm phát triển và xử lý sự cố","AI Agent Capstone vì cộng đồng"]};
Object.keys(frameworkLessons).forEach(g=>data[g].lessons=frameworkLessons[g]);
const standards={6:"6.A1–A3 · 6.B1–B2 · 6.C1–C3 · 6.D1–D2",7:"7.A1–A3 · 7.B2–B3 · 7.C4–C5 · 7.D1–D2",8:"8.A1–A3 · 8.B1–B3 · 8.C1/C5 · 8.D1–D2",9:"9.A1–A3 · 9.B2–B3 · 9.C2/C4 · 9.D1–D2",10:"10.A1–A3 · 10.B2–B3 · 10.C2–C4 · 10.D1–D2",11:"11.A1–A3 · 11.B2–B3 · 11.C2/C3/C5 · 11.D1–D2",12:"12.A1–A3 · 12.B1–B3 · 12.C2–C4 · 12.D1–D2"};
const outcomes={"Thực hành Teachable Machine":"Mô tả quy trình huấn luyện, tạo mô hình phân loại, kiểm thử bằng dữ liệu mới và giải thích ảnh hưởng của chất lượng dữ liệu.","Con người giữ quyền quyết định":"Giải thích vì sao con người cần giữ quyền quyết định để bảo đảm an toàn, công bằng và quyền lợi.","AI không thay thế con người":"Nêu lĩnh vực AI không nên thay thế con người và giải thích dựa trên cảm xúc, đạo đức, sáng tạo.","Prompt phù hợp mục tiêu":"Mô tả và thực hành các yêu cầu để tạo prompt phù hợp một mục tiêu cụ thể.","AI Agent Capstone vì cộng đồng":"Thiết kế, kiểm thử và đánh giá một tác nhân AI đơn giản với quyền kiểm soát của con người."};
const modules=["NLa · LẤY CON NGƯỜI LÀM TRUNG TÂM","NLb · ĐẠO ĐỨC AI","NLc · KĨ THUẬT VÀ ỨNG DỤNG","NLd · THIẾT KẾ HỆ THỐNG AI"];
let grade=7,active=7,query="";let done=JSON.parse(localStorage.getItem("ai-progress")||"[]");
const $=id=>document.getElementById(id);const outcome=t=>outcomes[t]||`Hoàn thành hoạt động học tập về “${t}”, trình bày bằng chứng và phản tư về trách nhiệm của người học.`;
function setGrade(g){grade=+g;active=0;render()};function setLesson(i){active=i;renderPlan();document.querySelector("#ke-hoach").scrollIntoView({behavior:"smooth"})}
function toggle(i){const k=`${grade}-${i}`;done=done.includes(k)?done.filter(x=>x!==k):[...done,k];localStorage.setItem("ai-progress",JSON.stringify(done));renderLessons()}
function render(){const g=data[grade];$("grades").innerHTML=Object.keys(data).map(x=>`<button class="${+x===grade?'active':''}" onclick="setGrade(${x})">${x}</button>`).join("");$("path").innerHTML='<p>LỘ TRÌNH 6–12</p>'+Object.keys(data).map((x,i)=>`<button class="${+x===grade?'active':''}" onclick="setGrade(${x})"><span>0${i+1}</span><b>${data[x].role}</b><small>Khối ${x}</small></button>`).join("");$("summary").innerHTML=`<div><span class="number">${grade}</span><p>KHỐI</p></div><div><p class="eyebrow">${g.name}</p><h3>${g.vn}</h3><blockquote>“${g.message}”</blockquote></div><dl><div><dt>Vai trò</dt><dd>${g.role}</dd></div><div><dt>Sản phẩm cuối</dt><dd>${g.product}</dd></div><div><dt>Prompting</dt><dd>${g.prompt}</dd></div></dl>`;renderLessons();renderPlan();renderMatrix()}
function renderLessons(){const g=data[grade];$("lessons").innerHTML=g.lessons.map((t,i)=>({t,i})).filter(x=>(x.t+outcome(x.t)).toLowerCase().includes(query)).map(({t,i})=>{const k=`${grade}-${i}`;return `<article class="${active===i?'selected':''}" onclick="setLesson(${i})"><div class="lesson-top"><span>TIẾT ${String(i+1).padStart(2,'0')}</span><button aria-label="Đánh dấu hoàn thành" onclick="event.stopPropagation();toggle(${i})">${done.includes(k)?'✓':'○'}</button></div><h4>${t}</h4><p>${outcome(t)}</p><footer><span>${modules[Math.floor(i/3)]}</span><b>Xem kế hoạch →</b></footer></article>`}).join("");const p=Math.round(g.lessons.filter((_,i)=>done.includes(`${grade}-${i}`)).length/12*100);$("bar").style.width=p+"%";$("progressText").textContent=p+"% hoàn thành"}
function renderPlan(){const g=data[grade],t=g.lessons[active];$("lessonNo").textContent=`Tiết ${active+1}`;$("asideTitle").textContent=t;$("module").textContent=`KHỐI ${grade} • ${modules[Math.floor(active/3)]}`;$("planTitle").textContent=t;$("objective").innerHTML=`<b>Học sinh có thể:</b> ${outcome(t)}`;$("lessonNav").innerHTML=g.lessons.map((x,i)=>`<button class="${i===active?'active':''}" onclick="setLesson(${i})"><span>${String(i+1).padStart(2,'0')}</span>${x}</button>`).join("");$("tmLab").innerHTML=grade===7&&active>=7?`<div class="tm-lab"><div><p class="eyebrow">TEACHABLE MACHINE LAB</p><h3>Huấn luyện mô hình, không thu thập dữ liệu cá nhân</h3><p>Tạo 2–3 lớp ảnh đồ vật an toàn, mỗi lớp tối thiểu 30 mẫu; thay đổi góc nhìn và ánh sáng; kiểm thử bằng dữ liệu chưa dùng khi huấn luyện.</p><a href="https://teachablemachine.withgoogle.com/train/image" target="_blank" rel="noreferrer">Mở Teachable Machine ↗</a></div><ol><li><b>Đặt mục tiêu</b><span>Không sử dụng dữ liệu khuôn mặt.</span></li><li><b>Tạo dữ liệu</b><span>Cân bằng số mẫu và đa dạng điều kiện.</span></li><li><b>Train & Test</b><span>Kiểm thử với mẫu hoàn toàn mới.</span></li><li><b>Improve</b><span>Ghi lỗi, bổ sung dữ liệu và huấn luyện lại.</span></li></ol></div>`:""}
const topicKnowledge={
"data": ["Dữ liệu là các ví dụ mà hệ thống AI dùng để tìm quy luật. Dữ liệu cần đúng, đủ, đa dạng và phù hợp mục đích.","Một mô hình phân loại đồ vật chỉ học từ ảnh được cung cấp; nó không thật sự ‘hiểu’ đồ vật như con người."],
"privacy": ["Dữ liệu cá nhân giúp nhận diện một người; dữ liệu nhạy cảm có thể gây tổn hại nếu bị lộ.","Chỉ cung cấp dữ liệu tối thiểu cần thiết. Không nhập họ tên đầy đủ, địa chỉ, mật khẩu, hồ sơ sức khỏe hoặc ảnh riêng tư vào công cụ AI."],
"bias": ["Thiên lệch xuất hiện khi dữ liệu hoặc cách thiết kế khiến kết quả bất lợi cho một số nhóm.","Công bằng không chỉ là độ chính xác trung bình; cần kiểm thử với nhiều nhóm và điều kiện sử dụng."],
"fact": ["Câu trả lời trôi chảy không đồng nghĩa với câu trả lời đúng. AI có thể tạo thông tin hoặc nguồn không tồn tại.","Kiểm chứng bằng ít nhất hai nguồn độc lập, ưu tiên nguồn chính thức, có tác giả và ngày cập nhật rõ ràng."],
"prompt": ["Prompt tốt nêu rõ nhiệm vụ, bối cảnh, đầu vào, định dạng và giới hạn phù hợp với mục tiêu.","Luôn đánh giá đầu ra rồi chỉnh prompt; không dùng prompt như mẹo để lấy đáp án nhanh."],
"generative": ["AI tạo sinh dự đoán thành phần tiếp theo để tạo văn bản, hình ảnh hoặc âm thanh mới dựa trên mẫu đã học.","Sản phẩm có thể hữu ích nhưng vẫn có lỗi, thiên lệch và vấn đề bản quyền; con người phải kiểm tra và biên tập."],
"system": ["Hệ thống AI gồm người dùng, dữ liệu, mô hình, giao diện, quy trình và điểm kiểm soát của con người.","Chất lượng toàn hệ thống phụ thuộc cả đầu vào, luật vận hành, phản hồi và cách xử lý khi AI sai."],
"risk": ["Rủi ro AI được đánh giá theo khả năng xảy ra và mức độ hậu quả đối với con người.","Giải pháp rủi ro cao cần giới hạn sử dụng, ghi nhận quyết định, cơ chế khiếu nại và giám sát của con người."],
"default": ["AI là công nghệ thực hiện các nhiệm vụ thường cần trí thông minh của con người bằng cách nhận ra quy luật từ dữ liệu.","AI hỗ trợ con người; người sử dụng vẫn chịu trách nhiệm kiểm chứng, quyết định và tác động của sản phẩm."]};
function category(t){t=t.toLowerCase();if(/data|dữ liệu|training|testing|classification|clustering|machine learning|teachable|supervised|unsupervised|reinforcement/.test(t))return"data";if(/privacy|cá nhân|an toàn|governance|footprint/.test(t))return"privacy";if(/bias|fairness|công bằng|social impact/.test(t))return"bias";if(/fact|hallucination|misinformation|deepfake|limitations/.test(t))return"fact";if(/prompt|đặt câu hỏi|context/.test(t))return"prompt";if(/generative|genai|llm|creativity|copyright|disclosure|integrity|tạo nội dung/.test(t))return"generative";if(/system|rag|nlp|language|vision|neural|prototype|lifecycle/.test(t))return"system";if(/risk|responsible|oversight|accountability|impact assessment|transparency|guardrail/.test(t))return"risk";return"default"}
function gradeNote(g){if(g<=7)return"Hãy dùng lời của em để giải thích và chọn ví dụ gần gũi trong lớp học hoặc gia đình.";if(g<=9)return"Hãy chỉ ra bằng chứng, so sánh nhiều khả năng và giải thích lựa chọn của em.";return"Hãy phân tích giả định, bên liên quan, rủi ro và đề xuất cơ chế kiểm soát có thể kiểm chứng."}
function lessonGuide(t,g){const c=category(t),k=topicKnowledge[c];const challenges={data:"Tạo một bảng 12 ví dụ chia thành 2–3 nhãn. Tìm một ví dụ khó phân loại và giải thích vì sao.",privacy:"Đọc một tình huống sử dụng AI ở trường. Gạch chân dữ liệu không nên chia sẻ và viết lại yêu cầu an toàn hơn.",bias:"Lập bảng kiểm thử cho ít nhất ba nhóm hoặc ba điều kiện khác nhau. So sánh kết quả và đề xuất cách giảm bất công.",fact:"Chọn một khẳng định do AI tạo. Dùng hai nguồn đáng tin cậy để xác nhận, bác bỏ hoặc bổ sung bối cảnh.",prompt:"Viết prompt lần 1, đánh giá theo tiêu chí rõ ràng, rồi sửa thành lần 2. Lưu cả hai phiên bản và nêu điều đã cải thiện.",generative:"Tạo một sản phẩm ngắn cùng AI, kiểm tra sự thật và bản quyền, sau đó ghi rõ phần AI hỗ trợ và phần em chỉnh sửa.",system:"Vẽ luồng Input → Model → Output → Human feedback. Đánh dấu nơi có thể xảy ra lỗi và nơi con người phải can thiệp.",risk:"Chọn một ứng dụng AI, xác định người được lợi/người có thể bị ảnh hưởng, mức rủi ro và hai biện pháp kiểm soát.",default:"Tìm hai ví dụ phù hợp và một phản ví dụ. Giải thích dấu hiệu giúp em phân biệt chúng."};return{concept:k,example:c==="data"?"Ví dụ: mô hình học ảnh bút và thước. Nếu mọi ảnh bút đều chụp trên bàn xanh, mô hình có thể học nhầm màu nền thay vì hình dạng.":c==="fact"?"Ví dụ: AI nêu một số liệu nhưng không cho biết báo cáo, tác giả hoặc năm. Đây là tín hiệu cần dừng lại và kiểm chứng.":c==="privacy"?"Ví dụ: hỏi AI góp ý bài viết không cần gửi họ tên, lớp, email hay ảnh thẻ học sinh.":c==="prompt"?"Ví dụ: ‘Hãy đóng vai gia sư, giải thích quang hợp cho học sinh lớp 8 bằng 120 từ, có ví dụ và 3 câu tự kiểm tra.’":"Ví dụ học tập cần được xem xét theo mục tiêu, dữ liệu đầu vào, chất lượng đầu ra và trách nhiệm của con người.",challenge:challenges[c],remember:c==="data"?"AI học từ mẫu trong dữ liệu, nên dữ liệu quyết định điều mô hình có thể làm.":c==="fact"?"Dừng – tìm nguồn – đối chiếu – kết luận.":c==="privacy"?"Không nhập dữ liệu cá nhân khi nhiệm vụ không thật sự cần.":c==="bias"?"Kiểm thử theo từng nhóm, không chỉ nhìn điểm trung bình.":c==="prompt"?"Prompt → đánh giá → sửa → kiểm chứng.":"AI hỗ trợ; con người kiểm chứng và chịu trách nhiệm.",note:gradeNote(g)}}
function quizItems(t,g){const c=category(t),bank={data:[["Điều nào giúp dữ liệu huấn luyện tốt hơn?",["Nhiều ví dụ đa dạng và đúng nhãn","Chỉ dùng các ví dụ giống hệt nhau","Bỏ qua dữ liệu kiểm thử"],0],["Dữ liệu kiểm thử nên được dùng khi nào?",["Sau huấn luyện để kiểm tra với mẫu mới","Trộn hết vào dữ liệu huấn luyện","Chỉ dùng để trang trí báo cáo"],0]],privacy:[["Thông tin nào không nên nhập vào AI cho một bài tập thông thường?",["Mật khẩu tài khoản","Tên chủ đề bài học","Số lượng từ mong muốn"],0],["Nguyên tắc phù hợp nhất là gì?",["Chỉ cung cấp dữ liệu tối thiểu cần thiết","Cung cấp mọi dữ liệu để AI hiểu hơn","Dùng thông tin của bạn bè khi chưa hỏi"],0]],bias:[["Cách nào giúp phát hiện thiên lệch?",["Kiểm thử trên nhiều nhóm và điều kiện","Chỉ thử một trường hợp thành công","Chỉ xem độ chính xác chung"],0],["Khi kết quả bất lợi cho một nhóm, em nên làm gì?",["Tìm nguyên nhân ở dữ liệu và thiết kế","Giấu kết quả","Kết luận AI luôn đúng"],0]],fact:[["Dấu hiệu nào đòi hỏi kiểm chứng?",["AI nêu số liệu nhưng không có nguồn rõ ràng","Câu trả lời có định dạng đẹp","Câu trả lời ngắn"],0],["Quy trình tốt nhất là gì?",["Đối chiếu ít nhất hai nguồn đáng tin cậy","Hỏi lại AI cùng một câu","Tin kết quả đầu tiên"],0]],prompt:[["Sau khi nhận đầu ra chưa tốt, bước tiếp theo là gì?",["Đánh giá lỗi rồi sửa prompt có chủ đích","Lặp lại nguyên prompt nhiều lần","Đổ lỗi hoàn toàn cho AI"],0],["Thành phần nào làm rõ hình thức câu trả lời?",["Format","Role","Input"],0]],generative:[["Ai chịu trách nhiệm cho sản phẩm cuối?",["Người sử dụng và công bố sản phẩm","Công cụ AI","Không ai"],0],["Hành động nào thể hiện trung thực?",["Khai báo phần AI hỗ trợ và phần mình chỉnh sửa","Xóa lịch sử làm việc","Nhận toàn bộ sản phẩm AI là của mình"],0]],system:[["Thành phần nào cần có trong hệ thống AI?",["Điểm kiểm soát và phản hồi của con người","Chỉ mô hình AI","Chỉ giao diện đẹp"],0],["Khi AI sai, thiết kế tốt cần gì?",["Quy trình phát hiện, sửa và chuyển cho người phụ trách","Tiếp tục tự động hóa","Ẩn lỗi với người dùng"],0]],risk:[["Rủi ro AI phụ thuộc vào điều gì?",["Khả năng xảy ra và mức độ hậu quả","Màu giao diện","Tên công cụ"],0],["Human oversight nghĩa là gì?",["Con người có quyền kiểm tra và can thiệp","AI tự quyết mọi việc","Chỉ kiểm tra sau khi có thiệt hại"],0]],default:[["Vai trò phù hợp nhất của AI là gì?",["Hỗ trợ con người thực hiện mục tiêu","Thay con người chịu trách nhiệm","Luôn đưa ra sự thật"],0],["Trước khi dùng đầu ra AI, em cần gì?",["Kiểm tra chất lượng và sự phù hợp","Sao chép ngay","Chỉ sửa hình thức"],0]]};return bank[c]}
function assessmentItems(t,g){const topical=quizItems(t,g);return[
  [`Trong chủ đề “${t}”, vai trò phù hợp nhất của con người là gì?`,["Đặt mục tiêu, kiểm tra và chịu trách nhiệm","Giao toàn bộ quyết định cho AI","Chỉ làm theo kết quả đầu tiên"],0,"NLa"],
  [`Khi học bài “${t}”, hành động nào thể hiện sử dụng AI có trách nhiệm?`,["Bảo vệ dữ liệu, kiểm chứng và khai báo hỗ trợ của AI","Sao chép kết quả mà không đọc lại","Dùng dữ liệu của người khác khi chưa được phép"],0,"NLb"],
  [topical[0][0],topical[0][1],topical[0][2],"NLc"],
  [`Nếu kết quả trong hoạt động “${t}” chưa đạt mục tiêu, em nên làm gì?`,["Xác định lỗi, điều chỉnh dữ liệu hoặc quy trình rồi kiểm thử lại","Giữ nguyên mọi thứ và chỉ đổi tên sản phẩm","Ẩn các trường hợp thất bại"],0,"NLd"]
]}

function renderMatrix(){const g=data[grade];$("matrixTitle").textContent=`Ma trận đánh giá Khối ${grade}`;$("matrixNote").innerHTML=`Mỗi bài có <b>4 câu tự kiểm tra</b>, mỗi câu gắn với một miền năng lực. Toàn khối có <b>48 câu</b>: 12 câu cho mỗi miền, tương ứng tỷ trọng 25%.`;$("matrixGrades").innerHTML=Object.keys(data).map(x=>`<button class="${+x===grade?'active':''}" onclick="setGrade(${x});document.querySelector('#ma-tran').scrollIntoView({behavior:'smooth'})">${x}</button>`).join("");$("matrixBody").innerHTML=g.lessons.map((t,i)=>{const items=assessmentItems(t,grade);return `<tr><th><span>Bài ${String(i+1).padStart(2,'0')}</span>${t}</th>${items.map((q,qi)=>`<td><b>${q[3]} · C${qi+1}</b><span>${q[0]}</span></td>`).join("")}</tr>`}).join("")}
function showView(view){document.querySelectorAll(".learn-tabs button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));["learn","practice","quiz"].forEach(v=>$(v+"View").hidden=v!==view)}
function renderQuiz(t){
  const items=assessmentItems(t,grade);
  const questions=items.map((q,qi)=>`<fieldset><legend><span>${qi+1}</span><b>${q[0]}</b><em>${q[3]}</em></legend>${q[1].map((a,ai)=>`<label><input type="radio" name="q${qi}" value="${ai}"><span>${a}</span></label>`).join("")}</fieldset>`).join("");
  $("quizView").innerHTML=`<div class="quiz-head"><p class="eyebrow">TỰ KIỂM TRA</p><h3>Em đã thực sự hiểu bài?</h3><p>Chọn đáp án cho từng câu rồi nhấn “Kiểm tra kết quả”. Em có thể làm lại.</p></div><form id="quizForm">${questions}<button type="button" class="check-quiz">Kiểm tra kết quả</button><div id="quizResult" class="quiz-result" aria-live="polite"></div></form>`;
  document.querySelector(".check-quiz").onclick=()=>{let score=0,missing=false;items.forEach((q,i)=>{const v=document.querySelector(`input[name=q${i}]:checked`);if(!v)missing=true;else if(+v.value===q[2])score++});const result=$("quizResult");if(missing){result.className="quiz-result warn";result.textContent="Em hãy trả lời đủ các câu trước khi kiểm tra.";return}const pass=score===items.length;result.className=`quiz-result ${pass?'pass':'retry'}`;result.innerHTML=pass?`<b>Xuất sắc! ${score}/${items.length} câu đúng.</b><span>Em đã nắm được ý chính. Hãy hoàn thành thử thách và đánh dấu bài học.</span>`:`<b>${score}/${items.length} câu đúng.</b><span>Hãy đọc lại phần Ghi nhớ và thử lại nhé.</span>`;localStorage.setItem(`quiz-${grade}-${active}`,String(score))};
}
renderPlan=function(){const g=data[grade],t=g.lessons[active],guide=lessonGuide(t,grade);$("lessonNo").textContent=`Bài ${active+1}`;$("asideTitle").textContent=t;$("module").textContent=`KHỐI ${grade} • ${modules[Math.floor(active/3)]}`;$("planTitle").textContent=t;$("objective").innerHTML=`<b>Sau bài này, em có thể:</b> ${outcome(t)}`;$("lessonNav").innerHTML=g.lessons.map((x,i)=>`<button class="${i===active?'active':''}" onclick="setLesson(${i})"><span>${String(i+1).padStart(2,'0')}</span>${x}</button>`).join("");$("learnView").innerHTML=`<div class="standard-strip"><b>Đối chiếu Khung 2422</b><span>${standards[grade]}</span></div><div class="study-grid"><article><p class="eyebrow">KIẾN THỨC TRỌNG TÂM</p><h3>${guide.concept[0]}</h3><p>${guide.concept[1]}</p></article><article class="example-card"><p class="eyebrow">VÍ DỤ</p><p>${guide.example}</p></article></div><div class="remember"><span>!</span><div><b>Ghi nhớ</b><p>${guide.remember}</p></div></div><p class="grade-note">${guide.note}</p><p class="access-note"><b>Phương án không tài khoản:</b> đọc nội dung trên trang, dùng phiếu in và dữ liệu mẫu do giáo viên cung cấp. Không nhập dữ liệu cá nhân; chỉ mở công cụ ngoài khi giáo viên đã rà soát.</p>`;$("practiceView").innerHTML=`<div class="challenge"><p class="eyebrow">THỬ THÁCH CỦA EM</p><h3>${t}</h3><p>${guide.challenge}</p><ol><li><b>Chuẩn bị</b><span>Xác định mục tiêu, dữ liệu hoặc nguồn cần dùng.</span></li><li><b>Thực hiện</b><span>Làm từng bước và lưu lại bằng chứng quan trọng.</span></li><li><b>Kiểm tra</b><span>Dùng tiêu chí của bài để tìm lỗi hoặc điểm còn thiếu.</span></li><li><b>Phản tư</b><span>Viết 2–3 câu: Em đã quyết định điều gì? Vì sao?</span></li></ol><div class="evidence"><b>Minh chứng cần nộp</b><span>Ảnh/bản sản phẩm • Learning Log • nguồn kiểm chứng • câu trả lời phản tư • khai báo AI</span></div></div>`;renderQuiz(t);$("tmLab").innerHTML=grade===7&&active>=7?`<div class="tm-lab"><div><p class="eyebrow">TEACHABLE MACHINE LAB</p><h3>Huấn luyện mô hình, bảo vệ dữ liệu cá nhân</h3><p>Tạo 2–3 lớp ảnh đồ vật an toàn, mỗi lớp ít nhất 30 mẫu; thay đổi góc nhìn và ánh sáng; dùng mẫu mới để kiểm thử.</p><a href="https://teachablemachine.withgoogle.com/train/image" target="_blank" rel="noreferrer">Mở Teachable Machine ↗</a></div><ol><li><b>1. Mục tiêu</b><span>Không dùng khuôn mặt hay dữ liệu nhận diện.</span></li><li><b>2. Dữ liệu</b><span>Cân bằng số mẫu và đa dạng điều kiện.</span></li><li><b>3. Train & Test</b><span>Kiểm thử với mẫu hoàn toàn mới.</span></li><li><b>4. Improve</b><span>Ghi lỗi, bổ sung dữ liệu, huấn luyện lại.</span></li></ol></div>`:"";$("prevLesson").disabled=active===0;$("nextLesson").disabled=active===11;$("completeLesson").textContent=done.includes(`${grade}-${active}`)?"Đã hoàn thành ✓":"Đánh dấu hoàn thành ✓";showView("learn")}
document.querySelectorAll(".learn-tabs button").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));$("prevLesson").onclick=()=>{if(active>0){active--;renderPlan();scrollTo({top:$("ke-hoach").offsetTop-70,behavior:"smooth"})}};$("nextLesson").onclick=()=>{if(active<11){active++;renderPlan();scrollTo({top:$("ke-hoach").offsetTop-70,behavior:"smooth"})}};$("completeLesson").onclick=()=>{toggle(active);renderPlan()};
$("search").addEventListener("input",e=>{query=e.target.value.toLowerCase();renderLessons()});$("print").onclick=()=>window.print();render();
