"use client";

import { useEffect, useMemo, useState } from "react";

type Lesson = { title: string; outcome: string };
type Grade = { grade: number; english: string; vietnamese: string; role: string; message: string; product: string; prompt: string; lessons: Lesson[] };

const curriculum: Grade[] = [
  { grade: 6, english: "AI Foundations", vietnamese: "AI quanh em và sử dụng AI an toàn", role: "AI Explorer", message: "AI hỗ trợ em, nhưng em vẫn chịu trách nhiệm.", product: "AI Learning Portfolio", prompt: "Task + Context + Output", lessons: [
    ["AI là gì?", "Phân biệt AI và công nghệ không phải AI; nhận biết ví dụ gần gũi."], ["AI quanh em", "Khám phá AI trong điện thoại, bản đồ, dịch thuật, đề xuất nội dung."], ["AI hoạt động như thế nào?", "Mô tả Data → Algorithm/Model → Output."], ["Con người và AI", "Nhận biết vai trò hỗ trợ của AI và trách nhiệm quyết định của con người."], ["AI có thể sai", "Nhận biết lỗi, hallucination và giới hạn của AI."], ["Fact-checking với AI", "Kiểm chứng thông tin bằng nguồn đáng tin cậy."], ["Dữ liệu cá nhân là gì?", "Nhận diện dữ liệu cá nhân và dữ liệu nhạy cảm trong tình huống học đường."], ["An toàn và quyền riêng tư", "Không chia sẻ dữ liệu không phù hợp cho AI."], ["Cách đặt câu hỏi hiệu quả", "Viết yêu cầu rõ ràng theo Task + Context + Output."], ["AI hỗ trợ học tập", "Dùng AI để giải thích, gợi ý, luyện tập nhưng không làm thay."], ["Human + AI Challenge", "Thực hiện quy trình hỏi rõ → kiểm tra → chỉnh sửa → chịu trách nhiệm."], ["Portfolio & Reflection", "Tổng hợp minh chứng, tự đánh giá và phản tư."]
  ].map(([title,outcome])=>({title,outcome})) },
  { grade: 7, english: "How Machines Learn", vietnamese: "Máy học từ dữ liệu", role: "AI Learner", message: "AI học từ dữ liệu; dữ liệu tốt hơn tạo ra AI tốt hơn.", product: "Mini Machine Learning Project", prompt: "Task + Context + Input + Output", lessons: [
    ["AI học khác con người?", "So sánh cách con người học và mô hình học từ dữ liệu."], ["Data – nhiên liệu của AI", "Hiểu vai trò của dữ liệu đối với hệ thống AI."], ["Thu thập và gán nhãn dữ liệu", "Tạo tập dữ liệu nhỏ có nhãn và nhận biết vấn đề chất lượng."], ["Training Data vs Testing Data", "Phân biệt dữ liệu huấn luyện và dữ liệu kiểm thử."], ["Supervised Learning", "Hiểu học có giám sát qua ví dụ phân loại."], ["Unsupervised Learning", "Hiểu ý tưởng nhóm dữ liệu theo đặc điểm."], ["Reinforcement Learning", "Hiểu nguyên tắc học qua phản hồi/phần thưởng."], ["Thực hành Teachable Machine", "Huấn luyện mô hình phân loại ảnh và mô tả nhiệm vụ theo 4 thành phần."], ["Bad Data → Bad AI", "Phân tích ảnh hưởng của dữ liệu thiếu, sai hoặc không đại diện."], ["Bias & Fairness", "Kiểm thử với nhiều người/điều kiện và nhận biết thiên lệch."], ["Mini AI Project", "Xác định mục tiêu, dữ liệu, bối cảnh và đầu vào cho mô hình."], ["Test – Improve – Present", "Kiểm thử, cải tiến dữ liệu/mô hình và trình bày bằng chứng."]
  ].map(([title,outcome])=>({title,outcome})) },
  { grade: 8, english: "Generative AI & Digital Responsibility", vietnamese: "AI tạo sinh và trách nhiệm số", role: "Responsible AI User", message: "Sáng tạo cùng AI, không sao chép từ AI.", product: "Responsible AI Creation", prompt: "Format + Constraint + Disclosure", lessons: [
    ["Từ Machine Learning đến GenAI", "Phân biệt AI dự đoán/phân loại với AI tạo sinh."], ["AI tạo nội dung thế nào?", "Khám phá văn bản, hình ảnh, âm thanh và giới hạn của GenAI."], ["AI Hallucination", "Phân tích câu trả lời có vẻ hợp lý nhưng sai."], ["Deepfake & Synthetic Media", "Nhận biết nội dung tổng hợp và nguy cơ gây hiểu lầm."], ["Recommendation & Manipulation", "Hiểu cá nhân hóa, thuật toán đề xuất và ảnh hưởng hành vi."], ["Privacy & Digital Footprint", "Đánh giá rủi ro dữ liệu khi dùng nền tảng AI."], ["Copyright thời GenAI", "Nhận biết quyền tác giả, nguồn và giới hạn sử dụng."], ["Academic Integrity", "Phân biệt hỗ trợ với gian lận; dùng Format và Constraint."], ["AI Disclosure", "Khai báo công cụ, prompt, phần AI tạo và phần học sinh chỉnh sửa."], ["Human Creativity vs AI", "Đánh giá vai trò sáng tạo, lựa chọn và biên tập của con người."], ["Responsible AI Creation", "Tạo sản phẩm bằng prompt có cấu trúc và quy trình minh bạch."], ["Peer Review & Reflection", "Đánh giá chéo và phản tư về trách nhiệm."]
  ].map(([title,outcome])=>({title,outcome})) },
  { grade: 9, english: "AI Problem Solving & Future Skills", vietnamese: "Giải quyết vấn đề và kỹ năng tương lai", role: "AI Problem Solver", message: "Đừng bắt đầu bằng AI. Hãy bắt đầu bằng một vấn đề.", product: "AI Solution Prototype", prompt: "Prompt → Evaluate → Revise", lessons: [
    ["AI đang thay đổi xã hội", "Nhận diện cơ hội và thách thức của AI trong đời sống."], ["Jobs & Skills in the AI Era", "Khám phá nghề nghiệp thay đổi dưới tác động AI."], ["Human Skills", "Xác định tư duy, sáng tạo, giao tiếp và phán đoán của con người."], ["AI Bias & Social Impact", "Phân tích hệ quả của thiên lệch AI."], ["Misinformation & Deepfake", "Nhận diện rủi ro thông tin sai và giả mạo."], ["Fact-checking Workflow", "Thiết lập quy trình kiểm chứng bằng nhiều nguồn."], ["Problem Finding", "Xác định vấn đề thực tế trong trường/cộng đồng."], ["Solution Ideation", "Đề xuất giải pháp, thử nhiều prompt và so sánh đầu ra."], ["Data Requirements", "Xác định dữ liệu cần thiết và rủi ro dữ liệu."], ["Build Prototype", "Xây nguyên mẫu và lưu Prompt Log."], ["Test – Evaluate – Improve", "Sửa prompt, dữ liệu hoặc giải pháp dựa trên bằng chứng."], ["AI Solution Pitch", "Trình bày giá trị, giới hạn và trách nhiệm."]
  ].map(([title,outcome])=>({title,outcome})) },
  { grade: 10, english: "AI Literacy & Prompt Engineering", vietnamese: "Hiểu biết AI và kỹ thuật viết prompt", role: "AI Collaborator", message: "Tư duy tốt hơn tạo ra prompt tốt hơn.", product: "AI Learning Assistant", prompt: "Role + Task + Context + Input + Format + Constraint", lessons: [
    ["Generative AI & LLM", "Hiểu vai trò của mô hình ngôn ngữ lớn ở mức trực quan."], ["Prediction vs Generation", "Phân biệt các dạng nhiệm vụ AI phổ biến."], ["LLM tạo câu trả lời", "Hiểu xác suất, ngữ cảnh và giới hạn ở mức phù hợp."], ["Hallucination & Limitations", "Đánh giá chất lượng và độ tin cậy đầu ra."], ["Prompt Engineering", "Hệ thống hóa kỹ năng đã tích lũy thành framework."], ["6 thành phần của Prompt", "Thực hành Role – Task – Context – Input – Format – Constraint."], ["Prompt Iteration", "Thiết kế tiêu chí, thử nghiệm và cải tiến prompt có hệ thống."], ["AI for Research", "Dùng AI tìm hướng nghiên cứu nhưng kiểm chứng nguồn."], ["AI for Learning", "Thiết kế cách dùng AI để giải thích, luyện tập và phản hồi."], ["AI for Creativity", "Kết hợp ý tưởng con người và khả năng tạo sinh."], ["Design an AI Learning Assistant", "Xây dựng trợ lý học tập cho một môn/chủ đề."], ["Test – Evaluate – Reflection", "Kiểm thử, đánh giá và phản tư về hiệu quả."]
  ].map(([title,outcome])=>({title,outcome})) },
  { grade: 11, english: "AI Systems & Intelligent Applications", vietnamese: "Hệ thống AI và ứng dụng thông minh", role: "AI System Designer", message: "Một sản phẩm AI là một hệ thống, không chỉ là chatbot.", product: "AI System Prototype", prompt: "Examples + System Instructions + Knowledge Context", lessons: [
    ["From AI Tool to AI System", "Nhìn AI như hệ thống gồm người dùng, dữ liệu, mô hình và quy trình."], ["Anatomy of an AI System", "Phân tích Input – Model – Output – Human Feedback."], ["Natural Language Processing", "Khám phá các ứng dụng xử lý ngôn ngữ."], ["Computer Vision", "Khám phá nhận dạng và phân tích hình ảnh."], ["Neural Networks", "Hiểu mạng nơ-ron ở mức khái niệm."], ["Classification & Clustering", "So sánh hai nhóm nhiệm vụ học máy cơ bản."], ["Advanced Prompting", "Thực hành few-shot examples và tiêu chí đầu ra."], ["System Instructions", "Phân biệt user prompt, system instructions và knowledge context."], ["RAG & Grounded Prompting", "Hiểu cách dùng nguồn kiến thức riêng để tạo câu trả lời có căn cứ."], ["AI System Design", "Thiết kế luồng dữ liệu và trải nghiệm người dùng."], ["Prototype Development", "Xây dựng nguyên mẫu no-code/low-code phù hợp."], ["Demonstration & Evaluation", "Trình diễn, đánh giá tính hữu ích, rủi ro và giới hạn."]
  ].map(([title,outcome])=>({title,outcome})) },
  { grade: 12, english: "Responsible AI Innovation", vietnamese: "Đổi mới AI có trách nhiệm", role: "Responsible AI Innovator", message: "AI làm được không có nghĩa là AI nên làm.", product: "AI Capstone Proposal", prompt: "Workflow + Guardrails + Human Oversight", lessons: [
    ["AI System Lifecycle", "Hiểu các giai đoạn từ nhu cầu đến vận hành và cải tiến."], ["Human Oversight", "Phân tích nơi con người phải kiểm soát/quyết định."], ["Responsible AI Principles", "Khám phá an toàn, công bằng, minh bạch và trách nhiệm."], ["AI Risk Classification", "Phân loại tình huống AI theo mức ảnh hưởng/rủi ro."], ["Privacy & Data Governance", "Đánh giá vòng đời dữ liệu, mục đích và quyền truy cập."], ["Fairness & Bias", "Phân tích công bằng và hệ quả với các nhóm người dùng."], ["Transparency & Guardrails", "Thiết kế chỉ dẫn và ràng buộc cho đầu ra."], ["Accountability", "Xác định trách nhiệm và điểm kiểm soát con người."], ["AI Impact Assessment", "Đánh giá tác động trước khi triển khai."], ["AI Capstone Design", "Thiết kế workflow, dữ liệu, guardrails và tiêu chí."], ["Risk Review & Improvement", "Rà soát rủi ro, kiểm soát và cải tiến."], ["AI Innovation Pitch", "Bảo vệ đề xuất dựa trên giá trị, minh chứng và trách nhiệm."]
  ].map(([title,outcome])=>({title,outcome})) },
];

const moduleNames = ["UNDERSTAND", "USE & EVALUATE", "ETHICS & RESPONSIBILITY", "CREATE"];
const flow = ["Khởi động", "Khám phá", "Thực hành", "Chia sẻ & phản tư"];

export default function Home() {
  const [selected, setSelected] = useState(7);
  const [activeLesson, setActiveLesson] = useState(7);
  const [query, setQuery] = useState("");
  const [done, setDone] = useState<string[]>([]);
  const grade = curriculum.find(g => g.grade === selected)!;
  useEffect(() => { const saved = localStorage.getItem("ai-curriculum-progress"); if (saved) setDone(JSON.parse(saved)); }, []);
  const toggleDone = (key:string) => setDone(prev => { const next = prev.includes(key) ? prev.filter(x=>x!==key) : [...prev,key]; localStorage.setItem("ai-curriculum-progress", JSON.stringify(next)); return next; });
  const visible = useMemo(() => grade.lessons.map((l,i)=>({...l,i})).filter(l => (l.title+l.outcome).toLowerCase().includes(query.toLowerCase())), [grade,query]);
  const lesson = grade.lessons[activeLesson];
  const progress = Math.round(grade.lessons.filter((_,i)=>done.includes(`${selected}-${i}`)).length/12*100);

  return <main>
    <header className="topbar"><a className="brand" href="#top"><span className="brandmark">AI</span><span>Khung chương trình AI<br/><small>Teacher Studio • Khối 6–12</small></span></a><nav><a href="#curriculum">Chương trình</a><a href="#lesson">Kế hoạch tiết dạy</a><button onClick={()=>window.print()}>In kế hoạch</button></nav></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">84 TIẾT • 7 KHỐI • 1 LỘ TRÌNH</p><h1>Dạy AI để học sinh<br/><em>hiểu, làm và chịu trách nhiệm.</em></h1><p className="lede">Không gian triển khai bài dạy dành cho giáo viên, bám sát chương trình 12 tiết mỗi khối và phát triển năng lực từ <b>USE AI</b> đến <b>GOVERN AI</b>.</p><div className="hero-actions"><a className="primary" href="#curriculum">Mở chương trình khối {selected} →</a><span>Tự lưu tiến độ trên thiết bị</span></div></div><div className="path"><p>LỘ TRÌNH 6–12</p>{curriculum.map((g,i)=><button className={selected===g.grade?"active":""} onClick={()=>{setSelected(g.grade);setActiveLesson(0)}} key={g.grade}><span>0{i+1}</span><b>{g.role}</b><small>Khối {g.grade}</small></button>)}</div></section>

    <section className="curriculum" id="curriculum"><div className="section-head"><div><p className="eyebrow">CHỌN KHỐI LỚP</p><h2>Một năm học. Mười hai điểm chạm.</h2></div><div className="grade-tabs" role="tablist">{curriculum.map(g=><button role="tab" aria-selected={selected===g.grade} className={selected===g.grade?"active":""} key={g.grade} onClick={()=>{setSelected(g.grade);setActiveLesson(0)}}>{g.grade}</button>)}</div></div>
      <div className="grade-summary"><div><span className="number">{grade.grade}</span><p>KHỐI</p></div><div><p className="eyebrow">{grade.english}</p><h3>{grade.vietnamese}</h3><blockquote>“{grade.message}”</blockquote></div><dl><div><dt>Vai trò</dt><dd>{grade.role}</dd></div><div><dt>Sản phẩm cuối</dt><dd>{grade.product}</dd></div><div><dt>Prompting</dt><dd>{grade.prompt}</dd></div></dl></div>
      <div className="toolbar"><label>⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm chủ đề hoặc đầu ra..."/></label><div className="progress"><span><i style={{width:`${progress}%`}}/></span><b>{progress}% hoàn thành</b></div></div>
      <div className="lesson-grid">{visible.map(l=>{const key=`${selected}-${l.i}`;return <article className={activeLesson===l.i?"selected":""} key={key} onClick={()=>setActiveLesson(l.i)}><div className="lesson-top"><span>TIẾT {String(l.i+1).padStart(2,"0")}</span><button aria-label="Đánh dấu hoàn thành" className={done.includes(key)?"checked":""} onClick={e=>{e.stopPropagation();toggleDone(key)}}>{done.includes(key)?"✓":"○"}</button></div><h4>{l.title}</h4><p>{l.outcome}</p><footer><span>{moduleNames[Math.floor(l.i/3)]}</span><b>Xem kế hoạch →</b></footer></article>})}</div>
    </section>

    <section className="planner" id="lesson"><aside><p className="eyebrow">KẾ HOẠCH TIẾT DẠY</p><h2>Tiết {activeLesson+1}</h2><p>{lesson.title}</p><div className="aside-nav">{grade.lessons.map((l,i)=><button className={i===activeLesson?"active":""} key={l.title} onClick={()=>setActiveLesson(i)}><span>{String(i+1).padStart(2,"0")}</span>{l.title}</button>)}</div></aside><div className="plan-content"><div className="plan-title"><div><p className="eyebrow">KHỐI {selected} • {moduleNames[Math.floor(activeLesson/3)]}</p><h2>{lesson.title}</h2></div><span>45 phút</span></div><p className="objective"><b>Học sinh có thể:</b> {lesson.outcome}</p><div className="flow">{flow.map((x,i)=><div key={x}><span>{i+1}</span><h3>{x}</h3><b>{[5,10,20,10][i]}′</b><p>{i===0?"Gợi mở bằng tình huống gần gũi và nêu câu hỏi trọng tâm.":i===1?"Quan sát ví dụ, thảo luận cặp đôi và hình thành khái niệm.":i===2?"Hoàn thành nhiệm vụ theo nhóm; giáo viên quan sát và phản hồi.":"Trình bày bằng chứng, tự đánh giá và ghi Learning Log."}</p></div>)}</div>
        {selected===7 && activeLesson>=7 && <div className="tm-lab"><div><p className="eyebrow">TEACHABLE MACHINE LAB</p><h3>Huấn luyện mô hình, không thu thập dữ liệu cá nhân</h3><p>Học sinh tạo 2–3 lớp ảnh đồ vật an toàn trong lớp, mỗi lớp tối thiểu 30 mẫu, thay đổi góc nhìn và ánh sáng, sau đó kiểm thử bằng dữ liệu chưa dùng khi huấn luyện.</p><a href="https://teachablemachine.withgoogle.com/train/image" target="_blank" rel="noreferrer">Mở Teachable Machine ↗</a></div><ol><li><b>Đặt mục tiêu</b><span>Viết rõ mô hình cần phân loại gì và không dùng dữ liệu khuôn mặt.</span></li><li><b>Tạo dữ liệu</b><span>Cân bằng số mẫu, đa dạng nền, góc và khoảng cách.</span></li><li><b>Train & Test</b><span>Huấn luyện rồi kiểm thử với mẫu hoàn toàn mới.</span></li><li><b>Improve</b><span>Ghi lỗi, bổ sung dữ liệu có chủ đích và huấn luyện lại.</span></li></ol></div>}
        <div className="teacher-kit"><h3>Bộ công cụ giáo viên</h3><div><button onClick={()=>window.print()}>▣ Phiếu kế hoạch tiết dạy</button><button onClick={()=>alert("Gợi ý minh chứng: Learning Log, ảnh sản phẩm, bảng kiểm thử và phản tư của học sinh.")}>＋ Minh chứng học tập</button><button onClick={()=>alert("Exit ticket: 1 điều em hiểu, 1 bằng chứng em có, 1 câu hỏi còn lại.")}>↗ Exit ticket</button></div></div>
      </div></section>
    <section className="assessment"><div><p className="eyebrow">ĐÁNH GIÁ VÌ SỰ TIẾN BỘ</p><h2>Đánh giá điều học sinh hiểu,<br/>không chỉ điều AI tạo ra.</h2></div><div className="rubric">{["AI Understanding","Effective AI Use","Critical Evaluation","Responsible & Ethical Use","Human Creativity & Contribution"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><em>20%</em></div>)}</div></section>
    <footer className="footer"><div className="brand"><span className="brandmark">AI</span><span>Khung chương trình AI<br/><small>Phiên bản triển khai giáo viên</small></span></div><p>Nguồn nội dung: LSTS AI Literacy & Responsible Innovation Program • Grades 6–12 • v1.1</p><a href="#top">Về đầu trang ↑</a></footer>
  </main>;
}
